version: '3'
networks:
  restaurant_network:
    driver: bridge

services:
  redis:
    image: redis
    platform: linux/x86_64
    ports:
      - 6379:6379
    
    networks:
      - restaurant_network

  database:
    image: postgres
    platform: linux/x86_64
    ports: 
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=restaurant
    networks:
      - restaurant_network

  restaurant:
    build:
      context: .
    ports:
      - 8181:8181
    env_file: 
      - .env

    depends_on:
      - redis
      - database

    networks:
      - restaurant_network
    
volumes:
  db:
    driver: local


